// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rjmcmcNucleo
List rjmcmcNucleo(SEXP startPosForwardReads, SEXP startPosReverseReads, long nbrIterations, int kMax, int lambda, int minInterval, int maxInterval, int minReads, bool adaptIterationsToReads, int vSeed);
RcppExport SEXP RJMCMCNucleosomes_rjmcmcNucleo(SEXP startPosForwardReadsSEXP, SEXP startPosReverseReadsSEXP, SEXP nbrIterationsSEXP, SEXP kMaxSEXP, SEXP lambdaSEXP, SEXP minIntervalSEXP, SEXP maxIntervalSEXP, SEXP minReadsSEXP, SEXP adaptIterationsToReadsSEXP, SEXP vSeedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type startPosForwardReads(startPosForwardReadsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type startPosReverseReads(startPosReverseReadsSEXP);
    Rcpp::traits::input_parameter< long >::type nbrIterations(nbrIterationsSEXP);
    Rcpp::traits::input_parameter< int >::type kMax(kMaxSEXP);
    Rcpp::traits::input_parameter< int >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type minInterval(minIntervalSEXP);
    Rcpp::traits::input_parameter< int >::type maxInterval(maxIntervalSEXP);
    Rcpp::traits::input_parameter< int >::type minReads(minReadsSEXP);
    Rcpp::traits::input_parameter< bool >::type adaptIterationsToReads(adaptIterationsToReadsSEXP);
    Rcpp::traits::input_parameter< int >::type vSeed(vSeedSEXP);
    rcpp_result_gen = Rcpp::wrap(rjmcmcNucleo(startPosForwardReads, startPosReverseReads, nbrIterations, kMax, lambda, minInterval, maxInterval, minReads, adaptIterationsToReads, vSeed));
    return rcpp_result_gen;
END_RCPP
}
