// This file was automatically generated by 'Kmisc::registerFunctions()'

#include <R.h>
#include <Rinternals.h>

#include <R_ext/Rdynload.h>

SEXP RJMCMCNucleosomes_rjmcmcNucleo(SEXP startPosForwardReadsSEXP, SEXP startPosReverseReadsSEXP, SEXP nbrIterationsSEXP, SEXP kMaxSEXP, SEXP lambdaSEXP, SEXP minIntervalSEXP, SEXP maxIntervalSEXP, SEXP minReadsSEXP, SEXP adaptIterationsToReadsSEXP, SEXP vSeedSEXP);

R_CallMethodDef callMethods[]  = {
  {"C_RJMCMCNucleosomes_rjmcmcNucleo", (DL_FUNC) &RJMCMCNucleosomes_rjmcmcNucleo, 10},
  {NULL, NULL, 0}
};

void R_init_RJMCMCNucleosomes(DllInfo *info) {
  R_registerRoutines(info, NULL, callMethods, NULL, NULL);
  R_useDynamicSymbols(info, FALSE);
}

