# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rjmcmcNucleo <- function(startPosForwardReads, startPosReverseReads, nbrIterations, kMax, lambda, minInterval, maxInterval, minReads = 5L, adaptIterationsToReads = TRUE, vSeed = -1L) {
    .Call('RJMCMCNucleosomes_rjmcmcNucleo', PACKAGE = 'RJMCMCNucleosomes', startPosForwardReads, startPosReverseReads, nbrIterations, kMax, lambda, minInterval, maxInterval, minReads, adaptIterationsToReads, vSeed)
}

